name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 16.x]
        typescript: [~4.3.2, ~4.4.2, ~4.5.2, ~4.6.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm install --save-dev typescript@${{ matrix.typescript }}
      - run: npm list --depth=0
      - run: npm run build
      - run: npm run lint
      - run: npm test
